# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 01:41
from __future__ import unicode_literals

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
